version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: Microsoft.Extensions.Configuration.AzureAppConfiguration
    versions:
    - 4.1.0
    - 4.2.0
  - dependency-name: Microsoft.FeatureManagement
    versions:
    - 2.2.0
  - dependency-name: Microsoft.FeatureManagement.AspNetCore
    versions:
    - 2.2.0
